// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BBadges: typeof import('./src/components/b-badges/index.vue')['default']
    BFilesTree: typeof import('./src/components/b-files-tree/index.vue')['default']
    BLayout: typeof import('./src/components/b-layout/index.vue')['default']
    BLayoutMenu: typeof import('./src/components/b-layout/b-layout-menu.vue')['default']
    BMarkdown: typeof import('./src/components/b-markdown/index.vue')['default']
    BPageTitle: typeof import('./src/components/b-page-title/index.vue')['default']
    BPercentChart: typeof import('./src/components/b-percent-chart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
