// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BAvatar: typeof import('./src/components/b-avatar/index.vue')['default']
    BBadges: typeof import('./src/components/b-badges/index.vue')['default']
    BFilesTree: typeof import('./src/components/b-files-tree/index.vue')['default']
    BLayout: typeof import('./src/components/b-layout/index.vue')['default']
    BLayoutMenu: typeof import('./src/components/b-layout/b-layout-menu.vue')['default']
    BMarkdown: typeof import('./src/components/b-markdown/index.vue')['default']
    BPageTitle: typeof import('./src/components/b-page-title/index.vue')['default']
    BPercentChart: typeof import('./src/components/b-percent-chart/index.vue')['default']
    BProjectCard: typeof import('./src/components/b-project-card/index.vue')['default']
    BSearch: typeof import('./src/components/b-search/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FilesTreeIcon: typeof import('./src/components/b-files-tree/files-tree-icon.vue')['default']
    Input: typeof import('./src/components/b-search/components/Input.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/b-search/components/Select.vue')['default']
  }
}

export {}
